### ISSUE TITLE
Acceptable Oneliner?

### ISSUE THREAD

**Issue by TechWiz-3** [cristaloleg/awesome-oneliners#5]
Thank you for your work on this project.

Does this count as a one-liner for your project? Just asking because I know it's a little simplistic. I use it whenever the ethernet dongle on my laptop starts playing up and I want to know when I've been connected to the internet.

```sh
ping google.com || while [[ $? != 0 ]] ; do ping google.com; done
```

If yes, let me know and I'll open a PR 👍

**Comment by cristaloleg** [comment]
Yeah, go for it ;)
